In [1]:
import selenium
from bs4 import BeautifulSoup
import requests
from selenium.common.exceptions import NoSuchElementException,StaleElementReferenceException,ElementClickInterceptedException
from selenium import webdriver
import time as time
import pandas as pd

In [2]:
driver = webdriver.Chrome(r"C:\Users\ASUS\Downloads\chromedriver_win32\chromedriver.exe")

In [7]:
url = "https://www.amazon.in"
driver.get(url)

In [4]:
search = driver.find_element_by_xpath('//input[@id="twotabsearchtextbox"]')

In [6]:
product = input("Enter the Product name you wish to search on Amazon :")

Enter the Product name you wish to search on Amazon :laptop

In [7]:
product = product+"s"
try:
    search.send_keys(product)
    btn = driver.find_element_by_xpath('//input[@id="nav-search-submit-button"]')
    btn.click()
    time.sleep(3)
except StaleElementReferenceException as e:
    print("Already open :",e)
    driver.get(driver.current_url)
    time.sleep(2)

**Q2. In the above question, now scrape the following details of each product listed in first 3 pages of your search results and save it in a data frame and csv. In case if any product vertical has less than 3 pages in search results then scrape all the products available under that product vertical. Details to be scraped are: "Brand Name", "Name of the Product", "Rating", "No. of Ratings", "Price", "Return/Exchange", "Expected Delivery", "Availability", "Other Details" and “Product URL”. In case, if any of the details are missing for any of the product then replace it by “-“.**

In [44]:
#Creating list to store information
brand =[]
Name =[]
Rating =[]
n_rating =[]
price = []
return_exchange =[]
expected_delivery =[]
availability = []
other = []
product_url = []

In [9]:
#Page urls
urls = []
for i in driver.find_elements_by_xpath('//div[@class="a-text-center"]//a'):
    urls.append(i.get_attribute('href'))

In [45]:
# Product Urls
for i in urls:
    driver.get(i)
    for j in driver.find_elements_by_xpath('//h2[@class="a-size-mini a-spacing-none a-color-base s-line-clamp-2"]//a'):
        product_url.append(j.get_attribute('href'))

In [46]:
for i in product_url:
    driver.get(i)
    
    try:
        for i in driver.find_elements_by_xpath('//td[@class="a-span9"]'):
            brand.append(i.text)
    except NoSuchElementException:
        brand.append("---")
            
    
    try:
        name = driver.find_element_by_xpath('//span[@class="a-size-large product-title-word-break"]')
        Name.append(name.text)
    except NoSuchElementException:
        Name.append("---")
    
    try:
        rating = driver.find_element_by_xpath('//span[@class="a-size-medium a-color-base"]')
        Rating.append(rating.text)
    except NoSuchElementException:
        Rating.append("---")
    
    try:
        N_r = driver.find_element_by_xpath('//div[@class="a-row a-spacing-medium averageStarRatingNumerical"]//span')
        n_rating.append(N_r.text)
    except NoSuchElementException:
        n_rating.append("---")
    
    
    try:
        prices = driver.find_element_by_xpath('//span[@id="priceblock_ourprice"]')
        price.append(prices.text)
    except NoSuchElementException:
        price.append("--")
    
    
    try:
        returns = driver.find_element_by_xpath('//div[@id="RETURNS_POLICY"]//a')
        if returns.text is None:
            return_exchange.append("---")
        else:
            return_exchange.append(returns.text)
    
    except NoSuchElementException:
        return_exchange.append("---")
    
    
    
    try:
        exp = driver.find_element_by_xpath('//div[@id="ddmDeliveryMessage"]//b')
        if exp.text is None:
            exepected_delivery.append("---")
        else:
            expected_delivery.append(exp.text)
    
    except NoSuchElementException:
        expected_delivery.append("---")
    
    
    try:
        avail = driver.find_element_by_xpath('//div[@id="availability"]//span')
        if avail.text is None:
            avail.append("---")
        else:
            availability.append(avail.text)
    except NoSuchElementException:
        avail.append("---")

In [62]:
Brand = brand[1::5]

In [65]:
OTher = brand[2::5]

In [68]:
import pandas as pd
product_details = pd.DataFrame({"Brand Name": Brand,"Name of the Product":Name,"Rating":Rating,"No. of Ratings":n_rating,
                          "Prices":price,"Return/Exchange":return_exchange,"Expected Delivery":expected_delivery,
                          "Availability":availability,"Other Details(Specified use for)":OTher})

product_details

,Brand Name,Name of the Product,Rating,No. of Ratings,Prices,Return/Exchange,Expected Delivery,Availability,Other Details(Specified use for)
0,Lenovo,Lenovo IdeaPad Gaming 3 Intel Core i5 10th Gen...,4.1 out of 5,15 global ratings,"₹56,990.00",7 Days Replacement,"Saturday, Aug 28",In stock.,"Personal, Gaming, Business"
1,Lenovo,Lenovo IdeaPad Slim 3 2021 11th Gen Intel Core...,3.9 out of 5,26 global ratings,"₹56,990.00",7 Days Replacement,"Friday, Aug 27",In stock.,"Multimedia, Personal, Business"
2,HP,"HP 15 (2021) Thin & Light Ryzen 3-3250 Laptop,...",3.8 out of 5,"1,270 global ratings","₹37,590.00",7 Days Replacement,"Friday, Aug 27",In stock.,Personal
3,HP,"HP 15 AMD Athlon 15.6"" (39.62cms) HD Laptop (S...",3.5 out of 5,325 global ratings,"₹29,632.00",7 Days Replacement,"Friday, Aug 27",In stock.,Personal
4,HP,HP Chromebook x360 Intel Celeron N4020 Process...,4.1 out of 5,250 global ratings,"₹29,990.00",7 Days Replacement,Oct 2 - 6,"In stock on September 30, 2021.",Personal
...,...,...,...,...,...,...,...,...,...
83,HP,HP Pavilion (2021) Thin & Light 11th Gen Core ...,4.4 out of 5,836 global ratings,"₹66,990.00",7 Days Replacement,Oct 1 - 4,"In stock on September 29, 2021.",Multimedia
84,HP,"HP 15 11th Gen Intel Core i3 Processor 15.6"" (...",3.6 out of 5,242 global ratings,"₹42,490.00",7 Days Replacement,"Friday, Aug 27",In stock.,Personal
85,Lenovo,Lenovo IdeaPad Slim 3 10th Gen Intel Core i3 1...,3.8 out of 5,445 global ratings,"₹38,990.00",7 Days Replacement,"Saturday, Aug 28",In stock.,"Multimedia, Personal, Business"
86,HP,"HP 15 11th Gen Intel Core i3 Processor 15.6"" (...",4 out of 5,716 global ratings,"₹45,390.00",7 Days Replacement,"Friday, Aug 27",In stock.,Multimedia
87,HP,HP Pavilion (2021) Thin & Light 11th Gen Core ...,4.4 out of 5,836 global ratings,"₹66,990.00",7 Days Replacement,"Saturday, Aug 28",In stock.,Multimedia

**3. Write a python program to access the search bar and search button on images.google.com and scrape 100 images each for keywords ‘fruits’, ‘cars’ and ‘Machine Learning’.**

In [3]:
driver.get("https://images.google.com")

In [162]:
search_bar = driver.find_element_by_xpath('//input[@class="gLFyf gsfi"]')
search_btn = driver.find_element_by_xpath('//button[@class="Tg7LZd"]')

In [163]:
search_bar.send_keys("Fruits")

In [164]:
search_btn.click()

In [165]:
for i in range(2):
    driver.execute_script("window.scrollBy(0,2000)","")

images = driver.find_elements_by_xpath('//img[@class="rg_i Q4LuWd"]')

# Extracting images urls
f_images_urls = []
try:
    for i in range(0,len(images)):
        images[i].click()
        for j in driver.find_elements_by_xpath('//img[@class="n3VNCb"]'):
            if j.get_attribute('src') and 'https' in j.get_attribute('src'):
                f_images_urls.append(j.get_attribute('src'))
    
except ElementClickInterceptedException:
    pass

In [171]:
# Searching for machine images
driver.get("https://images.google.com")

In [174]:
search_bar = driver.find_element_by_xpath('//input[@class="gLFyf gsfi"]')
search_btn = driver.find_element_by_xpath('//button[@class="Tg7LZd"]')
search_bar.send_keys("Machine Learning")
search_btn.click()

In [176]:
# to scroll down
for i in range(2):
    driver.execute_script("window.scrollBy(0,2000)","")

machine = driver.find_elements_by_xpath('//img[@class="rg_i Q4LuWd"]')
machine_learning_url = []
# Extracting images urls

try:
    for i in range(0,len(machine)):
        machine[i].click()
        for j in driver.find_elements_by_xpath('//img[@class="n3VNCb"]'):
            if j.get_attribute('src') and 'https' in j.get_attribute('src'):
                machine_learning_url.append(j.get_attribute('src'))
                if len(machine_learning_url)==100:# Only 100 images
                    break
except ElementClickInterceptedException:
    pass

In [178]:
driver.get("https://images.google.com")
search_bar = driver.find_element_by_xpath('//input[@class="gLFyf gsfi"]')
search_btn = driver.find_element_by_xpath('//button[@class="Tg7LZd"]')
search_bar.send_keys("cars")
search_btn.click()

In [179]:
# Searching for cars
cars = []


# to scroll down
for i in range(2):
    driver.execute_script("window.scrollBy(0,2000)","")

car = driver.find_elements_by_xpath('//img[@class="rg_i Q4LuWd"]')

# Extracting images urls
for i in range(0,len(car)):
    car[i].click()
    for j in driver.find_elements_by_xpath('//img[@class="n3VNCb"]'):
        if j.get_attribute('src') and 'https' in j.get_attribute('src'):
            cars.append(j.get_attribute('src'))
            if len(cars)==100:# Only 100 images
                break

In [182]:
# creating dataframe of links of images
images = pd.DataFrame({"Fruits":f_images_urls[:100],"Machine Learning":machine_learning_url[:100],
                      "Cars":cars[:100]})

images

,Fruits,Machine Learning,Cars
0,https://images-na.ssl-images-amazon.com/images...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://stimg.cardekho.com/images/carexteriori...
1,https://i.ytimg.com/vi/PY2OxP_jMZ0/maxresdefau...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://www.ft.com/__origami/service/image/v2/...
2,https://i.pinimg.com/originals/8a/6b/44/8a6b44...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://ichef.bbci.co.uk/news/976/cpsprodpb/15...
3,https://www.healthyeating.org/images/default-s...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://thumbor.forbes.com/thumbor/960x0/https...
4,https://images-na.ssl-images-amazon.com/images...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://hips.hearstapps.com/hmg-prod.s3.amazon...
...,...,...,...
95,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...
96,https://images.indianexpress.com/2020/06/fruit...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://images.hindustantimes.com/auto/img/202...
97,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...
98,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...
99,https://hips.hearstapps.com/hmg-prod.s3.amazon...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://hips.hearstapps.com/hmg-prod.s3.amazon...

**4. Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on www.flipkart.com and scrape following details for all the search results displayed on 1st page. Details to be scraped: “Brand Name”, “Smartphone name”, “Colour”, “RAM”, “Storage(ROM)”, “Primary Camera”, “Secondary Camera”, “Display Size”, “Display Resolution”, “Processor”, “Processor Cores”, “Battery Capacity”, “Price”, “Product URL”. Incase if any of the details is missing then replace it by “- “. Save your results in a dataframe and CSV.**

In [276]:
driver.get("https://www.flipkart.com/")

In [277]:
# Closing the popup
try:
    driver.find_element_by_xpath('//button[@class="_2KpZ6l _2doB4z"]').click()
except :
    pass

In [278]:
search = driver.find_element_by_xpath('//input[@title="Search for products, brands and more"]')
search_btn = driver.find_element_by_xpath('//button[@class="L0Z3Pu"]')

In [279]:
# Taking input from the user
product = input("Enter the Smartphone name you want to search :")

Enter the Smartphone name you want to search :m3pro

In [280]:
search.send_keys(product)
search_btn.click()

In [290]:
time.sleep(3)
urls = []
for i in driver.find_elements_by_xpath('//a[@class="_1fQZEK"]'):
    urls.append(i.get_attribute('href'))

In [291]:
brand = []
color=[] 
phone_name = []
details =[]
RAM = []
storage=[]
pcamera = []
scamera = []
Display_size = [] 
Display_resolution = []
processor = [] 
processor_cores=[]
Battery=[] 
price=[]

In [292]:
try:
    for i in driver.find_elements_by_xpath('//div[@class="_4rR01T"]'):
        brand.append(i.text)
except NoSuchElementException:
    brand.append("----")

In [293]:
for i in driver.find_elements_by_xpath('//div[@class="_30jeq3 _1_WHN1"]'):
    price.append(i.text)

In [294]:
for i in urls:
    driver.get(i)
    read_more = driver.find_element_by_xpath('//button[@class="_2KpZ6l _1FH0tX"]')
    read_more.click()
    
    
    try:
        colour = driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[9]/div[5]/div/div[2]/div[1]/div[1]/table/tbody/tr[4]/td[2]/ul/li')
        color.append(colour.text)   
    except NoSuchElementException:
        color.append("---")
    
    try:
        Processor =  driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[9]/div[5]/div/div[2]/div[1]/div[3]/table/tbody/tr[2]/td[2]/ul/li')
        processor.append(Processor.text)
    
    except NoSuchElementException:
        processor.append("---")
    
    try:
        battery = driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[9]/div[5]/div/div[2]/div[1]/div[9]/table/tbody/tr/td[2]/ul/li')
        Battery.append(battery.text)
    
    except NoSuchElementException:
        Battery.append("---")
    
    try:
        ram = driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[9]/div[5]/div/div[2]/div[1]/div[4]/table/tbody/tr[2]/td[2]/ul/li')
        RAM.append(ram.text)
    except NoSuchElementException :
        RAM.append("--")
    
    try:
        store = driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[9]/div[5]/div/div[2]/div[1]/div[4]/table/tbody/tr[1]/td[2]/ul/li')
        storage.append(store.text)
    except NoSuchElementException :
        storage.append("--")
    
    try:
        camera1 = driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[9]/div[5]/div/div[2]/div[1]/div[5]/table/tbody/tr[2]/td[2]/ul/li')
        pcamera.append(camera1.text)
    except NoSuchElementException :
        pcamera.append("--")
        
    try:
        camera2 = driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[9]/div[5]/div/div[2]/div[1]/div[5]/table/tbody/tr[5]/td[2]/ul/li')
        scamera.append(camera2.text)
    except NoSuchElementException :
        scamera.append("--")
        
    try:
        display_size = driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[9]/div[5]/div/div[2]/div[1]/div[2]/table/tbody/tr[1]/td[2]/ul/li')
        Display_size.append(display_size.text)
    except NoSuchElementException :
        Display_size.append("--")
    
    
    try:
        display_resolution = driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[9]/div[5]/div/div[2]/div[1]/div[2]/table/tbody/tr[2]/td[2]/ul/li')
        Display_resolution.append(display_resolution.text)
        
    except NoSuchElementException :
        Display_resolution.append("--")
        
    try:
        cores = driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[9]/div[5]/div/div[2]/div[1]/div[3]/table/tbody/tr[3]/td[2]/ul/li')
        processor_cores.append(cores.text)
        
    except NoSuchElementException :
        processor_cores.append("--")

In [296]:
flipkart = pd.DataFrame({"Brand Name":brand,"Smartphone name":brand,"Colour":color,"RAM":RAM,"Storage(ROM)":storage,
                         "Primary Camera":pcamera,"Secondary Camera":scamera,"Display Size":Display_size,"Display Resolution":Display_resolution,
                        "Processor":processor,"Processor Cores":processor_cores,"Battery Capacity":Battery,"Price":price,"Product URL":urls})
flipkart.head()

,Brand Name,Smartphone name,Colour,RAM,Storage(ROM),Primary Camera,Secondary Camera,Display Size,Display Resolution,Processor,Processor Cores,Battery Capacity,Price,Product URL
0,"POCO M3 Pro 5G (Yellow, 128 GB)","POCO M3 Pro 5G (Yellow, 128 GB)",Yellow,6 GB,128 GB,48MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch),2400 x 1080 Pixels,MediaTek Dimensity 700,Octa Core,5000 mAh,"₹15,999",https://www.flipkart.com/poco-m3-pro-5g-yellow...
1,"POCO M3 Pro 5G (Cool Blue, 128 GB)","POCO M3 Pro 5G (Cool Blue, 128 GB)",Cool Blue,6 GB,128 GB,48MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch),2400 x 1080 Pixels,MediaTek Dimensity 700,Octa Core,5000 mAh,"₹15,999",https://www.flipkart.com/poco-m3-pro-5g-cool-b...
2,"POCO M3 Pro 5G (Cool Blue, 64 GB)","POCO M3 Pro 5G (Cool Blue, 64 GB)",Cool Blue,4 GB,64 GB,48MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch),2400 x 1080 Pixels,MediaTek Dimensity 700,Octa Core,5000 mAh,"₹13,999",https://www.flipkart.com/poco-m3-pro-5g-cool-b...
3,"POCO M3 Pro 5G (Power Black, 64 GB)","POCO M3 Pro 5G (Power Black, 64 GB)",Power Black,4 GB,64 GB,48MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch),2400 x 1080 Pixels,MediaTek Dimensity 700,Octa Core,5000 mAh,"₹13,999",https://www.flipkart.com/poco-m3-pro-5g-power-...
4,"POCO M3 Pro 5G (Yellow, 64 GB)","POCO M3 Pro 5G (Yellow, 64 GB)",Yellow,4 GB,64 GB,48MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch),2400 x 1080 Pixels,MediaTek Dimensity 700,Octa Core,5000 mAh,"₹13,999",https://www.flipkart.com/poco-m3-pro-5g-yellow...

In [298]:
flipkart.to_csv("phones_details.csv")

**5. Write a program to scrap geospatial coordinates (latitude, longitude) of a city searched on google maps.**

In [311]:
import re

In [299]:
driver.get("https://maps.google.co.in")

In [300]:
time.sleep(3)
search = driver.find_element_by_xpath('//input[@id="searchboxinput"]')

In [301]:
# taking input from the user
city = input("Enter a city which geospatial coordinates you want to know :")# Asking for input
search.send_keys(city)

Enter a city which geospatial coordinates you want to know :bhopal

In [320]:
driver.find_element_by_xpath('//button[@id="searchbox-searchbutton"]').click()

In [332]:
url_string = driver.current_url
print("URL Extracted: ", url_string)

URL Extracted:  https://www.google.co.in/maps/place/Bhopal,+Madhya+Pradesh/@23.199663,77.2654611,11z/data=!4m5!3m4!1s0x397c428f8fd68fbd:0x2155716d572d4f8!8m2!3d23.2599333!4d77.412615

In [338]:
lat_lng = re.findall(r'@(.*)data',url_string)
lat_lng

['23.199663,77.2654611,11z/']

**6. Write a program to scrap details of all the funding deals for second quarter (i.e. July 20 –
September 20) from trak.in.**

In [268]:
driver.get("https://www.trak.in/")

In [269]:
driver.find_element_by_xpath('//a[@title="http://trak.in/india-startup-funding-investment-2015/"]').click()

In [289]:
# I have fetched all the information in one go then separeate it using indexing
july=[]
for i in driver.find_elements_by_xpath('//table[@class="tablepress tablepress-id-48 dataTable no-footer"]//td'):
    july.append(i.text)

In [290]:
aug = []
for i in driver.find_elements_by_xpath('//table[@id="tablepress-49"]//td'):
    aug.append(i.text)

In [291]:
sep = []
for i in driver.find_elements_by_xpath('//table[@class="tablepress tablepress-id-50 dataTable no-footer"]//td'):
    sep.append(i.text)

In [292]:
s_no=[]
date=[]
company=[]
ind_ver=[]
sub_ver = []
city = []
inves_name = []
inves_type = []
amt = []
remain=[]

In [293]:
# Filtering all the data
for i in range(0,len(july),9):
    s_no.append(july[i])
    
for i in range(1,len(july),9):
    date.append(july[i])
    
for i in range(2,len(july),9):
    company.append(july[i])
    
for i in range(3,len(july),9):
    ind_ver.append(july[i])
    
for i in range(4,len(july),9):
    sub_ver.append(july[i])

    
for i in range(5,len(july),9):
    city.append(july[i])

for i in range(6,len(july),9):
    inves_name.append(july[i])
    
for i in range(7,len(july),9):
    inves_type.append(july[i])
    
for i in range(8,len(july),9):
    amt.append(july[i])

In [294]:
# Filtering all the data
for i in range(0,len(aug),9):
    s_no.append(aug[i])
    
for i in range(1,len(aug),9):
    date.append(aug[i])
    
for i in range(2,len(aug),9):
    company.append(aug[i])
    
for i in range(3,len(aug),9):
    ind_ver.append(aug[i])
    
for i in range(4,len(aug),9):
    sub_ver.append(aug[i])

    
for i in range(5,len(aug),9):
    city.append(aug[i])

for i in range(6,len(aug),9):
    inves_name.append(aug[i])
    
for i in range(7,len(aug),9):
    inves_type.append(aug[i])
    
for i in range(8,len(aug),9):
    amt.append(aug[i])

In [295]:
# Filtering all the data
for i in range(0,len(sep),9):
    s_no.append(sep[i])
    
for i in range(1,len(sep),9):
    date.append(sep[i])
    
for i in range(2,len(sep),9):
    company.append(sep[i])
    
for i in range(3,len(sep),9):
    ind_ver.append(sep[i])
    
for i in range(4,len(sep),9):
    sub_ver.append(sep[i])

    
for i in range(5,len(sep),9):
    city.append(sep[i])

for i in range(6,len(sep),9):
    inves_name.append(sep[i])
    
for i in range(7,len(sep),9):
    inves_type.append(sep[i])
    
for i in range(8,len(sep),9):
    amt.append(sep[i])

In [299]:
trek = pd.DataFrame({"S.no":s_no,"Date":date,"Start-Up Name":company,"Industry/vertical":ind_ver,"Sub-Vertical":sub_ver,
                    "City":city,"Investment Name":inves_name,"Investment_type":inves_type,"Amount(In usd)":amt})
trek

,S.no,Date,Start-Up Name,Industry/vertical,Sub-Vertical,City,Investment Name,Investment_type,Amount(In usd)
0,1,15/07/2020,Flipkart,E-commerce,E-commerce,Bangalore,Walmart Inc,M&A,"1,200,000,000"
1,2,16/07/2020,Vedantu,EduTech,Online Tutoring,Bangalore,Coatue Management,Series D,"100,000,000"
2,3,16/07/2020,Crio,EduTech,Learning Platform for Developers,Bangalore,021 Capital,pre-Series A,"934,160"
3,4,14/07/2020,goDutch,FinTech,Group Payments,Mumbai,"Matrix India,Y Combinator, Global Founders Cap...",Seed,"1,700,000"
4,5,13/07/2020,Mystifly,Airfare Marketplace,"Ticketing, Airline Retailing, and Post-Ticketi...",Singapore and Bangalore,Recruit Co. Ltd.,pre-Series B,"3,300,000"
5,6,09/07/2020,JetSynthesys,Gaming and Entertainment,Gaming and Entertainment,Pune,Adar Poonawalla and Kris Gopalakrishnan.,Venture-Series Unknown,"400,000"
6,7,10/07/2020,gigIndia,Marketplace,"Crowd Sourcing, Freelance",Pune,Incubate Fund India and Beyond Next Ventures,pre-Series A,"974,200"
7,8,15/07/2020,PumPumPum,Automotive Rental,Used Car-leasing platform,Gurgaon,Early Adapters Syndicate,Seed,"292,800"
8,9,14/07/2020,FLYX,OTT Player,Streaming Social Network,New York and Delhi,"Raj Mishra, founder of AIT Global Inc",pre-Seed,"200,000"
9,10,13/07/2020,Open Appliances Pvt. Ltd.,Information Technology,Internet-of-Things Security Solutions,Bangalore,Unicorn India Ventures,Venture-Series Unknown,"500,000"
10,1,15/08/2020,Practo,HealthTech,Health care and Wellness,Bangalore,A1A Company,Series F,"32,000,000"
11,2,13/08/2020,Medlife,E-commerce,Online Pharmacy,Bangalore,Prasid Uno Family Trust and SC Credit Fund,,"23,000,000"
12,3,13/08/2020,HungerBox,FoodTech,Online Food Delivery Service,Bangalore,"One97, Sabre Partners Trust, Pratithi Investme...",Series D1,"1,560,000"
13,4,04/08/2020,Dunzo,Hyper-local Logistics,Online Delivery Services,Bangalore,Existing Backers,In Progress,"30,000,000"
14,5,11/08/2020,Terra.do,EduTech,"Online Climate School, E-learning","Stanford, California,","Stanford Angels and Entrepreneurs (India), BEE...",Seed,"1,400,000"
15,6,12/08/2020,Classplus,EduTech,"E-learning, Online Tutoring",Noida,Falcon Edge,In Progress,"upto 15,000,000"
16,7,14/08/2020,Niyo,FinTech,Financial Services,Bangalore,Niyo Solutions Inc.,,"6,000,000"
17,8,10/08/2020,ZestMoney,FinTech,Financial Services,Bangalore,Primrose Hills Ventures,,"10,670,000"
18,9,07/08/2020,FreshToHome,E-commerce,Food Delivery,Bangalore,Ascent Capital,Venture,"16,200,000"
19,10,13/08/2020,Eduvanz,FinTech,Financial Services,Mumbai,"Sequoia India, Unitus",Series A,"5,000,000"
20,11,03/08/2020,CrowdPouch,FinTech,Financial Services,Bangalore,Elina Investments Pvt. Ltd,Angel,NA
21,12,04/08/2020,DrinkPrime,Water Purification,Water Purification,Bangalore,"Sequoia Surge, ON Mauritius",Pre-Series A,"2,880,000"
22,1,08/09/2020,Byju’s,EduTech,Online Tutoring,Bangalore,"Silver Lake, Tiger Global, General Atlantic an...",Private Equity,"500,000,000"
23,2,12/09/2020,mCaffeine,Personal Care,Skincare & Haircare,Mumbai,"Amicus Capital Private Equity I LLP, Amicus Ca...",Series B,"3,000,000"
24,3,09/09/2020,Qshala,EduTech,Online Curiosity Platform for Kids,Bangalore,Rainmatter Capital,Angel,"370,000"
25,4,02/09/2020,Winzo,Online Gaming,Online Gaming,New Delhi,"Kalaari Capital Partners, IndigoEdge Managemen...",Series B,"15,500,000"
26,5,09/09/2020,Hippo Video,Video Customer Experience(CX) Platform,Video Customer Experience(CX) Platform,"Newark, Delaware, United States of Amercia","Alpha Wave Incubation, Exfinity Venture Partne...",Series A,"4,500,000"
27,6,07/09/2020,Melorra,E-commerce,Online Jewelry Store,Bangalore,"Shadow Holdings, Lightbox.",Debt Financing,"upto 8,900,000"
28,7,07/09/2020,1mg,E-commerce,Online Pharmacy,Gurgaon,"Gaja Capital, Tata Capital, Partners Group",In Progress,"100,000,000"
29,8,31/08/2020,mfine,HealthTech,On-Demand Healthcare Services,Bangalore,Caretech Pte Inc,Series B,"5,400,000"
30,9,31/08/2020,Apna,Human Resources,Recruitment Platform,Bangalore,Lightspeed India and Sequoia Capital India,Series A,"8,000,000"
31,10,03/09/2020,Railofy,Transportation,WL & RAC protection platform,Mumbai,Chiratae Ventures,Seed,"950,000"
32,11,08/09/2020,Cell Propulsion,Automobile,Electric Mobility Solutions,Bangalore,growX Ventures and Micelio,pre-Series A,NA

In [300]:
trek.to_csv("terk.csv")

**7. Write a program to scrap all the available details of best gaming laptops from digit.in.**

In [307]:
driver.get("https://www.digit.in/")

In [309]:
for i in driver.find_elements_by_xpath('//div[@class="listing_container"]'):
    if i.text == 'Best Gaming Laptops in India':
        i.click()

In [353]:
product = []
seller = []
price = []
details = []

for i in driver.find_elements_by_xpath('//div[@class="Top10-Seller"]//td'):
    details.append(i.text)
for i in range(0,len(details),3):
    product.append(details[i])

    
for i in range(1,len(details),3):
    if details[i] == 'N/A' or details[i] is None:
        seller.append("--")
    else:
        seller.append(details[i])
for i in range(2,len(details),3):
    if details[i]=='N/A' or details[i] is None:
        price.append("--")
    else:
        price.append(details[i])

In [379]:
rem = []
os = []
display = []
processor = []
memory = []

for i in driver.find_elements_by_xpath('//div[@class="value"]'):
    rem.append(i.text.replace(":",""))

In [388]:
os = rem[0::4]
display = rem [1::4]
processor = rem[2::4]
memory = rem[3::4]

In [389]:
digit = pd.DataFrame({"Product_Name":product,"Seller":seller,"Price":price,"Operating_System":os,"Display":display,
                     "Processor":processor,"Memory":memory})
digit

,Product_Name,Seller,Price,Operating_System,Display,Processor,Memory
0,Alienware Area 51M R2,--,--,WINDOWS 10 HOME,"17.3"" (1920 X 1080)",10TH GENERATION INTEL® CORE™ I7-10700 | 2.90 GHZ,1 TB SSD/16 GBGB DDR4
1,Alienware m15 R3,--,₹341990,WINDOWS 10 HOME,"15.6"" (3840 X 2160)",10TH GENERATION INTEL® CORE™ I9-10980HK | NA,1 TB SSD/16 GBGB DDR4
2,ASUS ROG Strix Scar 15,--,--,WINDOWS 10 HOME,"15.6"" (1920 X 1080)",AMD RYZEN™ 9 5900HX | 3.3 GHZ,1 TB SSD/16 GBGB DDR4
3,Asus ROG Zephyrus G14,amazon,₹164990,WINDOWS 10 HOME,"14"" (1920 X 1080)",AMD 3RD GENERATION RYZEN 9 | 3.3 GHZ,1 TB SSD/16 GBGB DDR4
4,Lenovo Legion 5i,amazon,₹76988,WINDOWS 10 PRO,"15.6"" (1920 X 1080)",10TH GENERATION INTEL® CORE™ I5-10300H | 2.50 GHZ,1 TB SSD/16 GBGB DDR4
5,ASUS ROG ZEPHYRUS DUO 15,amazon,₹185000,WINDOWS 10,"15.6"" (3840 X 1100)",INTEL CORE I7 10TH GEN 10875H | NA,512 GB SSD/4 GBGB DDR4
6,Acer Aspire 7 gaming,amazon,₹64370,WINDOWS 10 HOME,"15.6"" (1920 X 1080)",AMD RYZEN™ 5-5500U HEXA-CORE | NA,512 GB SSD/8 GBGB DDR4

**8. Write a python program to scrape the details for all billionaires from www.forbes.com. Details to be scrapped: “Rank”, “Name”, “Net worth”, “Age”, “Citizenship”, “Source”, “Industry”.**

In [82]:
driver.get("https://www.forbes.com/")
time.sleep(3)

In [83]:
btn = driver.find_element_by_xpath('//button[@class="icon--hamburger"]')
btn.click()

In [84]:
urls = []# to store all the limks
for i in driver.find_elements_by_xpath('//li[@data-title="Billionaires"]//a'):#getting all the links in Billionaires section
    urls.append(i.get_attribute('href'))

In [154]:
driver.get(urls[2])# We only need the world billionaires link which is present inside the urls at 2nd index position.

In [113]:
nxt_btn = driver.find_element_by_xpath('//div[@class="next-page"]')

In [179]:
#Creating blank list to store data
rank = []
name = []
net_worth = []
age = []
citizenship = []
source = []
industry =[]

In [180]:
for i in range(15):
    for i in driver.find_elements_by_xpath('//div[@class="rank"]'):
        rank.append(i.text)
    
    for i in driver.find_elements_by_xpath('//div[@class="personName"]'):
        name.append(i.text)
    
    for i in driver.find_elements_by_xpath('//div[@class="netWorth"]'):
        if i.text == 'N/A' or i.text == None:
            net_worth.append("--")
        else:
            net_worth.append(i.text)
    
    for i in driver.find_elements_by_xpath('//div[@class="age"]'):
        if i.text == 'N/A'or i.text == None:
            age.append("--")
        else:
            age.append(i.text)
    
    for i in driver.find_elements_by_xpath('//div[@class="countryOfCitizenship"]'):
        citizenship.append(i.text)
    
    for i in driver.find_elements_by_xpath('//div[@class="source"]'):
        if i.text == 'N/A' or i.text == None:
            source.append("--")
        else:
            source.append(i.text)
    
    for i in driver.find_elements_by_xpath('//div[@class="category"]'):
        if i.text == 'N/A' or i.text == None:
            industry.append("--")
        else:
            industry.append(i.text)
        
    try:
        nxt_btn = driver.find_element_by_xpath('//div[@class="next-page"]')
        if nxt_btn.click()==True:
            continue
    
    except ElementClickInterceptedException as ec:
        print("No more pages to click",ec)
        break

No more pages to click Message: element click intercepted: Element <div class="next-page">...</div> is not clickable at point (1419, 696). Other element would receive the click: <div class="pagination">...</div>
  (Session info: chrome=92.0.4515.159)

In [181]:
import pandas as pd
forbes = pd.DataFrame({"Rank":rank,"Name":name,"NetWorth":net_worth,"Age":age,"CitizenShip":citizenship,
                       "Source":source,"Industry":industry})
forbes

,Rank,Name,NetWorth,Age,CitizenShip,Source,Industry
0,1.,Jeff Bezos,$177 B,57,United States,Amazon,Technology
1,2.,Elon Musk,$151 B,49,United States,"Tesla, SpaceX",Automotive
2,3.,Bernard Arnault & family,$150 B,72,France,LVMH,Fashion & Retail
3,4.,Bill Gates,$124 B,65,United States,Microsoft,Technology
4,5.,Mark Zuckerberg,$97 B,36,United States,Facebook,Technology
...,...,...,...,...,...,...,...
2750,2674.,Daniel Yong Zhang,$1 B,49,China,e-commerce,Technology
2751,2674.,Zhang Yuqiang,$1 B,65,China,Fiberglass,Manufacturing
2752,2674.,Zhao Meiguang,$1 B,58,China,gold mining,Metals & Mining
2753,2674.,Zhong Naixiong,$1 B,58,China,conglomerate,Diversified
2754,2674.,Zhou Wei family,$1 B,54,China,Software,Technology

In [182]:
forbes.to_csv("Billionaires.csv")

__9. Write a program to extract at least 500 Comments, Comment upvote and time when comment was posted from any YouTube Video.__

In [253]:
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
wait = WebDriverWait(driver,10)
import time

In [44]:
driver.get("https://www.youtube.com/")

In [47]:
search = driver.find_element_by_xpath('//input[@id="search"]')
search.send_keys('Dil keh raha hai dil se')

In [48]:
btn = driver.find_element_by_xpath('//button[@class="style-scope ytd-searchbox"]')
btn.click()

In [49]:
driver.find_element_by_xpath('//yt-formatted-string[@class="style-scope ytd-video-renderer"]').click()

In [50]:
# Skipping the ads
time.sleep(5)
try:
    click = driver.find_element_by_xpath('//div[@class="ytp-ad-text ytp-ad-skip-button-text"]').click()
except:
    pass

In [51]:
#Creating blank list to store data
comments=[]
upvote = []
ctime = []

In [69]:
# for scrolling down to fetch more comments
for item in range(40):# Increase the range if you want to load more comments
    time.sleep(3)
    driver.execute_script("window.scrollBy(0,1000)","")

    
# extracting comment
for i in driver.find_elements_by_id("content-text"):
    comments.append(i.text)


#upvote    
for i in driver.find_elements_by_xpath('//span[@id="vote-count-middle"]'):
    if i.text is None:
        upvote.append("--")
    else:
        upvote.append(i.text)
        
# Comment time
for i in driver.find_elements_by_xpath('//yt-formatted-string[@class="published-time-text above-comment style-scope ytd-comment-renderer"]'):
    ctime.append(i.text)

In [77]:
import pandas as pd
youtube = pd.DataFrame({"Comments":comments[:500],"Comments upvote":upvote[:500],"Time when comment posted":ctime[:500]})

youtube

,Comments,Comments upvote,Time when comment posted
0,"if u r listing this song in 2021,salute u,beca...",572,6 months ago (edited)
1,"#Nostalgia , I was a kid when this album 'Tera...",173,4 months ago
2,Adnan's voice is like the feeling of first lov...,332,6 months ago
3,You're not alone sami.. million fan with you.....,76,5 months ago
4,"Dear 90s boys and girls, if you are listening ...",103,5 months ago
...,...,...,...
495,"Pure gold childhood days....days of dd metro,c...",11,2 years ago
496,I love songs ❤️❤️❤️❤️,,4 months ago
497,"Superb made our days in age of 17, 18......",,2 months ago
498,സൂപ്പർ💕💕💝💝💝,2,5 months ago
499,Beautiful,,4 months ago

### 10. Write a python program to scrape a data for all available Hostels from https://www.hostelworld.com/ in “London” location. You have to scrape hostel name, distance from city centre, ratings, total reviews, overall reviews, privates from price, dorms from price, facilities and property description.

In [108]:
driver.get("https://www.hostelworld.com/")

In [109]:
hostel = driver.find_element_by_xpath('//a[@title="Hostels"]')
hostel.click()

In [110]:
search = driver.find_element_by_xpath('//input[@id="home-search-keywords"]')
search.send_keys("London")
time.sleep(2)

In [111]:
btn = driver.find_element_by_xpath('//button[@class="btn btn-primary btn-block"]')
btn.click()

In [152]:
hostel=[]
urls =[]
distance = []
rating=[]
overall=[]
total_r =[]
facilities = []
price=[]

In [153]:
while True:
    
    for i in driver.find_elements_by_xpath('//h2[@class="title title-6"]'):
        hostel.append(i.text)
    
    for i in driver.find_elements_by_xpath('//h2[@class="title title-6"]//a'):
        urls.append(i.get_attribute('href'))
    
    for i in driver.find_elements_by_xpath('//div[@class="facilities-label facilities"]'):
        facilities.append(i.text.replace("\n",","))
    
    for i in driver.find_elements_by_xpath('//span[@class="description"]'):
        distance.append(i.text)
        
    for i in driver.find_elements_by_xpath('//div[@class="price-col"]'):
        if i.text is None:
            price.append("---")
        else:
            price.append(i.text.replace("\n"," "))
    try:
        time.sleep(2)
        driver.find_element_by_xpath('//div[@class="pagination-item pagination-next"]').click()
    
    except NoSuchElementException:
        print("No more pages to click")
        break

No more pages to click

In [154]:
description = []
overall_r=[]

In [161]:
for i in urls:
    driver.get(i)
    time.sleep(2)
    try:
        driver.find_element_by_xpath('//a[@class="toggle-content"]').click()# clicking on show more
    except NoSuchElementException:
        None
    
    desc = driver.find_element_by_xpath('//div[@class="collapsible"]/div[2]')
    if desc.text is None:
        description.append("---")
    else:
        description.append(desc.text)

In [164]:
for i in urls:
    driver.get(i)
    try:
        rat = driver.find_element_by_xpath('//div[@class="score orange big"]')
        rating.append(rat.text)
    except NoSuchElementException:
        rating.append("---")
        None

In [166]:
for i in urls:
    driver.get(i)
    try:
        over = driver.find_element_by_xpath('//div[@class="keyword"]')
        overall_r.append(over.text)
    except NoSuchElementException:
        overall_r.append("--")
        None

In [168]:
for i in urls:
    driver.get(i)    
    try:
        total = driver.find_element_by_xpath('//div[@class="reviews"]')
        if total.text is None:
            total_r.append("--")
        else:
            total_r.append(total.text)
    
    except NoSuchElementException:
        total_r.append("--")
        None

In [170]:
dorms = price[1::2]

In [171]:
private = price[0::2]

In [172]:
import pandas as pd
hostel = pd.DataFrame({"Hostel Name":hostel,"Distance from city center":distance,"Ratings":rating,"Total Reviews":total_r,
                      "Overall Reviews":overall_r,"Privates from price":private,"Dorms from price":dorms,"Facilities":facilities,
                      "property description":description})
hostel

,Hostel Name,Distance from city center,Ratings,Total Reviews,Overall Reviews,Privates from price,Dorms from price,Facilities,property description
0,London Waterloo Hostel,Hostel - 0.7km from city centre,7.6,2409 Total Reviews,Very Good,No Privates Available,Dorms From Rs1520,"Free WiFi,Free Breakfast,Follows Covid-19 sani...",COVID-19 Policy Update\n\nIn response to Coron...
1,Wombat's The City Hostel London,Hostel - 3.6km from city centre,9.2,13140 Total Reviews,Superb,Privates From Rs8064,Dorms From Rs1818,"Free WiFi,Follows Covid-19 sanitation guidance",Wombat's The City Hostel London is definitely ...
2,Prime Backpackers Angel,Hostel - 3.6km from city centre,10,513 Total Reviews,Superb,Privates From Rs6039,Dorms From Rs2397,"Free WiFi,Follows Covid-19 sanitation guidance",The hostel is housed in a historic building in...
3,St Christopher's Village,Hostel - 1.8km from city centre,8.9,10827 Total Reviews,Fabulous,Privates From Rs3445,Dorms From Rs1256,"Free WiFi,Follows Covid-19 sanitation guidance",Hostelworld visitors have said St Christopher'...
4,"PubLove @ The Steam Engine, Waterloo",Hostel - 0.5km from city centre,9.0,189 Total Reviews,Superb,Privates From Rs18643,Dorms From Rs1520,"Free WiFi,Follows Covid-19 sanitation guidance","The Steam Engine, Bestplace Inn is a great hos..."
...,...,...,...,...,...,...,...,...,...
77,The Dover,Hotel - 1.9km from city centre,---,0 Total Reviews,No Rating,Privates From Rs6788,No Dorms Available,"Free WiFi,Free Breakfast","With friendly staff, excellent service and an ..."
78,Park Hotel Essex,Hotel - 24.1km from city centre,---,0 Total Reviews,No Rating,Privates From Rs4154,No Dorms Available,"Free Breakfast,Follows Covid-19 sanitation gui...",This Hotel is the right choice for visitors wh...
79,Cranbrook Hotel,Hotel - 14.8km from city centre,---,0 Total Reviews,No Rating,Privates From Rs3951,No Dorms Available,"Free Breakfast,Follows Covid-19 sanitation gui...",We are located about twenty minutes by tube fr...
80,St. Athans,Bed and Breakfast - 2.9km from city centre,---,0 Total Reviews,No Rating,Privates From Rs4083,No Dorms Available,"Free WiFi,Follows Covid-19 sanitation guidance","The St Athans Hotel is a proudly simple, famil..."
81,Aron Guest House,Bed and Breakfast - 13.1km from city centre,---,0 Total Reviews,No Rating,Privates From Rs6586,No Dorms Available,Free WiFi,"Aron Guest House provides an excellent base, w..."

In [173]:
hostel.to_csv("hostel.csv")